version: "3"
volumes:
  data:
services:
  frontend:
    env_file:
      - .env.dev
    build:
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_WS_BASE: "wss://api.audio-hq.quest"
      tags:
        - jdkula/audio-hq-frontend:latest
    network_mode: host
    depends_on:
      - minio
      - mongodb
      - server
    ports:
      - '3000:3000'
  server:
    env_file:
      - .env.dev
    build:
      dockerfile: Dockerfile.server
      tags:
        - jdkula/audio-hq-server:latest
    network_mode: host
    depends_on:
      - minio
      - mongodb
    ports:
      - '3050:3050'
  worker:
    env_file:
      - .env.dev
    build:
      dockerfile: Dockerfile.worker
      tags:
        - jdkula/audio-hq-worker:latest
    network_mode: host
    depends_on:
      - minio
      - mongodb
      - server
  minio:
   profiles:
     - dev
   image: 'quay.io/minio/minio'
   command: 'server /data --console-address ":9090"'
   environment:
     MINIO_DOMAIN: localhost
   volumes:
     - './temp/test_data:/data'
   ports:
     - '9090:9090'
     - '9000:9000'
  mongodb:
   profiles:
     - dev
   image: 'mongo:latest'
   command: '--replSet local --bind_ip localhost,mongodb'
   environment:
     MONGODB_INITDB_ROOT_USERNAME: root
     MONGODB_INITDB_ROOT_PASSWORD: kula
   volumes:
    - 'data:/data/db'
   ports:
     - '27018:27017'
    