FROM node:24-bullseye AS base
WORKDIR /app

ENTRYPOINT [ ]

RUN npm install -g pnpm

FROM base AS builder

COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml /app/
RUN corepack enable
RUN pnpm install --frozen

FROM builder AS sourced
COPY . /app/
