# <-- Runner setup -->
FROM node:18-alpine AS builder
RUN npm install -g pnpm
WORKDIR /audio-hq
COPY ./pnpm-lock.yaml ./
RUN apk add --update --no-cache python3 libc6-compat alpine-sdk && ln -sf python3 /usr/bin/python
RUN pnpm fetch

COPY . ./
RUN pnpm install -r --offline
ARG NEXT_PUBLIC_WS_BASE="wss://api.audio-hq.quest"
RUN pnpm exec lerna run build --include-dependencies --scope @audio-hq/frontend
EXPOSE 3000

WORKDIR /audio-hq/packages/frontend
CMD ["pnpm", "start"]