steps:
  - label: ":docker: Initialize Buildx"
    command: 'echo "FROM scratch" | docker buildx build -'
    concurrency: 1
    concurrency_group: lanayru/docker-buildx
  - label: ":allthethings: :rocket: Initialize Release Build"
    if: build.tag != null && build.tag =~ /^release_.*/
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline.release.yml
  - label: ":allthethings: Initialize Dev Build"
    if: build.tag == null || build.tag !~ /^release_.*/
    commands:
      - buildkite-agent pipeline upload .buildkite/pipeline.dev.yml
